management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curso_springboot
    username: devdb
    password: a1b2c3d4

    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 300000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update   # <-- ANTES TENÃAS create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: curso-service

logging:
  level:
    root: ERROR
    web: INFO
    org:
      springframework: ERROR
      hibernate:
        SQL: DEBUG
    com:
      zaxxer:
        hikari: ERROR

server:
  port: 8082   # ESTE es tu puerto final del servicio

app:
  api:
    version: v1
  version: 1.14.0

semestre-service:
  url: http://localhost:8084

usuario-service:
  url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  instance:
    prefer-ip-address: true
